= The Kingsmill Release
:author: Jamie Duncan
:date: 2016-10-20 11:32
:modified: 2016-10-20 11:32
:slug: introducing-shadowbox
:summary: A quick write-up of the first iteration of Shadowbox
:category: Rev0
:tags: rev0,kingsmill
:gallery: kingsmill

== Kingsmill

Every year the Red Hat Public Sector Team has an off-site event. For the past few years it has been held at the link:https://www.kingsmill.com[Kingsmill Golf Resort]. It's a frantic 3 days of meetings, training, and networking. This year someone had the amazing idea of holding a _Demo Jam_.

== Demo Jam

The rules were pretty simple. You came up with the coolest demo you could think of using Red Hat products. You had 10 minutes after dinner on Wednesday night at Kingsmill to show it to everyone at the event (~350 people this year). After everyone was done, the team with the loudest applause won.

== Revision 0 - The Kingsmill release

We had gotten approval to put Shadowbox together a couple of months ago, but our day jobs had interfered with making much progress. We set ourselves a deadline of getting something ready for the Kingsmill Demo Jam. We didn't have to have the entire thing polished and ready, but it needed to show multiple products simultaneously.

We ended up getting 4 nodes up and running (we ran out of link:http://www.mini-box.com/s.nl/it.A/id.417/.f[Pico PSUs]). On these 4 nodes we were able to run:

=== The Infrastructure
* DNS and DHCP for the network
* RHEV-M on a physical node with DNS/DHCP
* Gluster on a single node
* 2 RHEL 7 hypervisors conncted to RHEV-M

On top of that we deployed:

=== The Platform
* OpenShift 3.3
* Configured to use the Gluster hardware node for Persistant Volume

Inside OpenShift we deployed a link:https://github.com/jduncan-rva/php-demo-app[PHP web app] that is a simple image uploader application.

=== The Demo
For our 10 minutes on stage we explained what we had made, and then we let everyone in the room connect to the Shadowbox's integrated Wifi. Since we control DNS in that network they were able to browse to our app deployed in OpenShift using an `example.com` domain.

We had a great time, and everything worked just like it was supposed to.
